export const SET_RECIPIENT_NAME = 'SET_RECIPIENT_NAME';
export const SET_RECIPIENT_ADDRESS = 'SET_RECIPIENT_ADDRESS';
export const SET_RECIPIENT_CITY = 'SET_RECIPIENT_CITY';
export const SET_RECIPIENT_STATE = 'SET_RECIPIENT_STATE';
export const SET_RECIPIENT_ZIPCODE = 'SET_RECIPIENT_ZIPCODE';
export const SET_RECIPIENT_COUNTRY = 'SET_RECIPIENT_COUNTRY';
