export const SET_SHIPPERS_NAME = 'SET_SHIPPERS_NAME';
export const SET_SHIPPERS_ADDRESS = 'SET_SHIPPERS_ADDRESS';
export const SET_SHIPPERS_CITY = 'SET_SHIPPERS_CITY';
export const SET_SHIPPERS_STATE = 'SET_SHIPPERS_STATE';
export const SET_SHIPPERS_ZIPCODE = 'SET_SHIPPERS_ZIPCODE';
export const SET_SHIPPERS_COUNTRY = 'SET_SHIPPERS_COUNTRY';
