export const COUNTRIES_ARRAY = [
  { content: { label: 'Afghanistan', value: 'AF' } },
  { content: { label: 'Aland Islands', value: 'AX' } },
  { content: { label: 'Albania', value: 'AL' } },
  { content: { label: 'Algeria', value: 'DZ' } },
  { content: { label: 'American Samoa', value: 'AS' } },
  { content: { label: 'AndorrA', value: 'AD' } },
  { content: { label: 'Angola', value: 'AO' } },
  { content: { label: 'Anguilla', value: 'AI' } },
  { content: { label: 'Antarctica', value: 'AQ' } },
  { content: { label: 'Antigua and Barbuda', value: 'AG' } },
  { content: { label: 'Argentina', value: 'AR' } },
  { content: { label: 'Armenia', value: 'AM' } },
  { content: { label: 'Aruba', value: 'AW' } },
  { content: { label: 'Australia', value: 'AU' } },
  { content: { label: 'Austria', value: 'AT' } },
  { content: { label: 'Azerbaijan', value: 'AZ' } },
  { content: { label: 'Bahamas', value: 'BS' } },
  { content: { label: 'Bahrain', value: 'BH' } },
  { content: { label: 'Bangladesh', value: 'BD' } },
  { content: { label: 'Barbados', value: 'BB' } },
  { content: { label: 'Belarus', value: 'BY' } },
  { content: { label: 'Belgium', value: 'BE' } },
  { content: { label: 'Belize', value: 'BZ' } },
  { content: { label: 'Benin', value: 'BJ' } },
  { content: { label: 'Bermuda', value: 'BM' } },
  { content: { label: 'Bhutan', value: 'BT' } },
  { content: { label: 'Bolivia', value: 'BO' } },
  { content: { label: 'Bosnia and Herzegovina', value: 'BA' } },
  { content: { label: 'Botswana', value: 'BW' } },
  { content: { label: 'Bouvet Island', value: 'BV' } },
  { content: { label: 'Brazil', value: 'BR' } },
  { content: { label: 'British Indian Ocean Territory', value: 'IO' } },
  { content: { label: 'Brunei Darussalam', value: 'BN' } },
  { content: { label: 'Bulgaria', value: 'BG' } },
  { content: { label: 'Burkina Faso', value: 'BF' } },
  { content: { label: 'Burundi', value: 'BI' } },
  { content: { label: 'Cambodia', value: 'KH' } },
  { content: { label: 'Cameroon', value: 'CM' } },
  { content: { label: 'Canada', value: 'CA' } },
  { content: { label: 'Cape Verde', value: 'CV' } },
  { content: { label: 'Cayman Islands', value: 'KY' } },
  { content: { label: 'Central African Republic', value: 'CF' } },
  { content: { label: 'Chad', value: 'TD' } },
  { content: { label: 'Chile', value: 'CL' } },
  { content: { label: 'China', value: 'CN' } },
  { content: { label: 'Christmas Island', value: 'CX' } },
  { content: { label: 'Cocos (Keeling) Islands', value: 'CC' } },
  { content: { label: 'Colombia', value: 'CO' } },
  { content: { label: 'Comoros', value: 'KM' } },
  { content: { label: 'Congo', value: 'CG' } },
  { content: { label: 'Congo, The Democratic Republic of the', value: 'CD' } },
  { content: { label: 'Cook Islands', value: 'CK' } },
  { content: { label: 'Costa Rica', value: 'CR' } },
  { content: { label: 'Cote DIvoire', value: 'CI' } },
  { content: { label: 'Croatia', value: 'HR' } },
  { content: { label: 'Cuba', value: 'CU' } },
  { content: { label: 'Cyprus', value: 'CY' } },
  { content: { label: 'Czech Republic', value: 'CZ' } },
  { content: { label: 'Denmark', value: 'DK' } },
  { content: { label: 'Djibouti', value: 'DJ' } },
  { content: { label: 'Dominica', value: 'DM' } },
  { content: { label: 'Dominican Republic', value: 'DO' } },
  { content: { label: 'Ecuador', value: 'EC' } },
  { content: { label: 'Egypt', value: 'EG' } },
  { content: { label: 'El Salvador', value: 'SV' } },
  { content: { label: 'Equatorial Guinea', value: 'GQ' } },
  { content: { label: 'Eritrea', value: 'ER' } },
  { content: { label: 'Estonia', value: 'EE' } },
  { content: { label: 'Ethiopia', value: 'ET' } },
  { content: { label: 'Falkland Islands (Malvinas)', value: 'FK' } },
  { content: { label: 'Faroe Islands', value: 'FO' } },
  { content: { label: 'Fiji', value: 'FJ' } },
  { content: { label: 'Finland', value: 'FI' } },
  { content: { label: 'France', value: 'FR' } },
  { content: { label: 'French Guiana', value: 'GF' } },
  { content: { label: 'French Polynesia', value: 'PF' } },
  { content: { label: 'French Southern Territories', value: 'TF' } },
  { content: { label: 'Gabon', value: 'GA' } },
  { content: { label: 'Gambia', value: 'GM' } },
  { content: { label: 'Georgia', value: 'GE' } },
  { content: { label: 'Germany', value: 'DE' } },
  { content: { label: 'Ghana', value: 'GH' } },
  { content: { label: 'Gibraltar', value: 'GI' } },
  { content: { label: 'Greece', value: 'GR' } },
  { content: { label: 'Greenland', value: 'GL' } },
  { content: { label: 'Grenada', value: 'GD' } },
  { content: { label: 'Guadeloupe', value: 'GP' } },
  { content: { label: 'Guam', value: 'GU' } },
  { content: { label: 'Guatemala', value: 'GT' } },
  { content: { label: 'Guernsey', value: 'GG' } },
  { content: { label: 'Guinea', value: 'GN' } },
  { content: { label: 'Guinea-Bissau', value: 'GW' } },
  { content: { label: 'Guyana', value: 'GY' } },
  { content: { label: 'Haiti', value: 'HT' } },
  { content: { label: 'Heard Island and Mcdonald Islands', value: 'HM' } },
  { content: { label: 'Holy See (Vatican City State)', value: 'VA' } },
  { content: { label: 'Honduras', value: 'HN' } },
  { content: { label: 'Hong Kong', value: 'HK' } },
  { content: { label: 'Hungary', value: 'HU' } },
  { content: { label: 'Iceland', value: 'IS' } },
  { content: { label: 'India', value: 'IN' } },
  { content: { label: 'Indonesia', value: 'ID' } },
  { content: { label: 'Iran, Islamic Republic Of', value: 'IR' } },
  { content: { label: 'Iraq', value: 'IQ' } },
  { content: { label: 'Ireland', value: 'IE' } },
  { content: { label: 'Isle of Man', value: 'IM' } },
  { content: { label: 'Israel', value: 'IL' } },
  { content: { label: 'Italy', value: 'IT' } },
  { content: { label: 'Jamaica', value: 'JM' } },
  { content: { label: 'Japan', value: 'JP' } },
  { content: { label: 'Jersey', value: 'JE' } },
  { content: { label: 'Jordan', value: 'JO' } },
  { content: { label: 'Kazakhstan', value: 'KZ' } },
  { content: { label: 'Kenya', value: 'KE' } },
  { content: { label: 'Kiribati', value: 'KI' } },
  { content: { label: 'Korea, Republic of', value: 'KR' } },
  { content: { label: 'Kuwait', value: 'KW' } },
  { content: { label: 'Kyrgyzstan', value: 'KG' } },
  { content: { label: 'Lao Peoples Democratic Republic', value: 'LA' } },
  { content: { label: 'Latvia', value: 'LV' } },
  { content: { label: 'Lebanon', value: 'LB' } },
  { content: { label: 'Lesotho', value: 'LS' } },
  { content: { label: 'Liberia', value: 'LR' } },
  { content: { label: 'Libyan Arab Jamahiriya', value: 'LY' } },
  { content: { label: 'Liechtenstein', value: 'LI' } },
  { content: { label: 'Lithuania', value: 'LT' } },
  { content: { label: 'Luxembourg', value: 'LU' } },
  { content: { label: 'Macao', value: 'MO' } },
  { content: { label: 'Macedonia, The Former Yugoslav Republic of', value: 'MK' } },
  { content: { label: 'Madagascar', value: 'MG' } },
  { content: { label: 'Malawi', value: 'MW' } },
  { content: { label: 'Malaysia', value: 'MY' } },
  { content: { label: 'Maldives', value: 'MV' } },
  { content: { label: 'Mali', value: 'ML' } },
  { content: { label: 'Malta', value: 'MT' } },
  { content: { label: 'Marshall Islands', value: 'MH' } },
  { content: { label: 'Martinique', value: 'MQ' } },
  { content: { label: 'Mauritania', value: 'MR' } },
  { content: { label: 'Mauritius', value: 'MU' } },
  { content: { label: 'Mayotte', value: 'YT' } },
  { content: { label: 'Mexico', value: 'MX' } },
  { content: { label: 'Micronesia, Federated States of', value: 'FM' } },
  { content: { label: 'Moldova, Republic of', value: 'MD' } },
  { content: { label: 'Monaco', value: 'MC' } },
  { content: { label: 'Mongolia', value: 'MN' } },
  { content: { label: 'Montenegro', value: 'ME' } },
  { content: { label: 'Montserrat', value: 'MS' } },
  { content: { label: 'Morocco', value: 'MA' } },
  { content: { label: 'Mozambique', value: 'MZ' } },
  { content: { label: 'Myanmar', value: 'MM' } },
  { content: { label: 'Namibia', value: 'NA' } },
  { content: { label: 'Nauru', value: 'NR' } },
  { content: { label: 'Nepal', value: 'NP' } },
  { content: { label: 'Netherlands', value: 'NL' } },
  { content: { label: 'Netherlands Antilles', value: 'AN' } },
  { content: { label: 'New Caledonia', value: 'NC' } },
  { content: { label: 'New Zealand', value: 'NZ' } },
  { content: { label: 'Nicaragua', value: 'NI' } },
  { content: { label: 'Niger', value: 'NE' } },
  { content: { label: 'Nigeria', value: 'NG' } },
  { content: { label: 'Niue', value: 'NU' } },
  { content: { label: 'Norfolk Island', value: 'NF' } },
  { content: { label: 'Northern Mariana Islands', value: 'MP' } },
  { content: { label: 'Norway', value: 'NO' } },
  { content: { label: 'Oman', value: 'OM' } },
  { content: { label: 'Pakistan', value: 'PK' } },
  { content: { label: 'Palau', value: 'PW' } },
  { content: { label: 'Palestinian Territory, Occupied', value: 'PS' } },
  { content: { label: 'Panama', value: 'PA' } },
  { content: { label: 'Papua New Guinea', value: 'PG' } },
  { content: { label: 'Paraguay', value: 'PY' } },
  { content: { label: 'Peru', value: 'PE' } },
  { content: { label: 'Philippines', value: 'PH' } },
  { content: { label: 'Pitcairn', value: 'PN' } },
  { content: { label: 'Poland', value: 'PL' } },
  { content: { label: 'Portugal', value: 'PT' } },
  { content: { label: 'Puerto Rico', value: 'PR' } },
  { content: { label: 'Qatar', value: 'QA' } },
  { content: { label: 'Reunion', value: 'RE' } },
  { content: { label: 'Romania', value: 'RO' } },
  { content: { label: 'Russian Federation', value: 'RU' } },
  { content: { label: 'RWANDA', value: 'RW' } },
  { content: { label: 'Saint Helena', value: 'SH' } },
  { content: { label: 'Saint Kitts and Nevis', value: 'KN' } },
  { content: { label: 'Saint Lucia', value: 'LC' } },
  { content: { label: 'Saint Pierre and Miquelon', value: 'PM' } },
  { content: { label: 'Saint Vincent and the Grenadines', value: 'VC' } },
  { content: { label: 'Samoa', value: 'WS' } },
  { content: { label: 'San Marino', value: 'SM' } },
  { content: { label: 'Sao Tome and Principe', value: 'ST' } },
  { content: { label: 'Saudi Arabia', value: 'SA' } },
  { content: { label: 'Senegal', value: 'SN' } },
  { content: { label: 'Serbia', value: 'RS' } },
  { content: { label: 'Seychelles', value: 'SC' } },
  { content: { label: 'Sierra Leone', value: 'SL' } },
  { content: { label: 'Singapore', value: 'SG' } },
  { content: { label: 'Slovakia', value: 'SK' } },
  { content: { label: 'Slovenia', value: 'SI' } },
  { content: { label: 'Solomon Islands', value: 'SB' } },
  { content: { label: 'Somalia', value: 'SO' } },
  { content: { label: 'South Africa', value: 'ZA' } },
  { content: { label: 'South Georgia and the South Sandwich Islands', value: 'GS' } },
  { content: { label: 'Spain', value: 'ES' } },
  { content: { label: 'Sri Lanka', value: 'LK' } },
  { content: { label: 'Sudan', value: 'SD' } },
  { content: { label: 'Suriname', value: 'SR' } },
  { content: { label: 'Svalbard and Jan Mayen', value: 'SJ' } },
  { content: { label: 'Swaziland', value: 'SZ' } },
  { content: { label: 'Sweden', value: 'SE' } },
  { content: { label: 'Switzerland', value: 'CH' } },
  { content: { label: 'Syrian Arab Republic', value: 'SY' } },
  { content: { label: 'Taiwan, Province of China', value: 'TW' } },
  { content: { label: 'Tajikistan', value: 'TJ' } },
  { content: { label: 'Tanzania, United Republic of', value: 'TZ' } },
  { content: { label: 'Thailand', value: 'TH' } },
  { content: { label: 'Timor-Leste', value: 'TL' } },
  { content: { label: 'Togo', value: 'TG' } },
  { content: { label: 'Tokelau', value: 'TK' } },
  { content: { label: 'Tonga', value: 'TO' } },
  { content: { label: 'Trinidad and Tobago', value: 'TT' } },
  { content: { label: 'Tunisia', value: 'TN' } },
  { content: { label: 'Turkey', value: 'TR' } },
  { content: { label: 'Turkmenistan', value: 'TM' } },
  { content: { label: 'Turks and Caicos Islands', value: 'TC' } },
  { content: { label: 'Tuvalu', value: 'TV' } },
  { content: { label: 'Uganda', value: 'UG' } },
  { content: { label: 'Ukraine', value: 'UA' } },
  { content: { label: 'United Arab Emirates', value: 'AE' } },
  { content: { label: 'United Kingdom', value: 'GB' } },
  { content: { label: 'United States', value: 'US' } },
  { content: { label: 'United States Minor Outlying Islands', value: 'UM' } },
  { content: { label: 'Uruguay', value: 'UY' } },
  { content: { label: 'Uzbekistan', value: 'UZ' } },
  { content: { label: 'Vanuatu', value: 'VU' } },
  { content: { label: 'Venezuela', value: 'VE' } },
  { content: { label: 'Viet Nam', value: 'VN' } },
  { content: { label: 'Virgin Islands, British', value: 'VG' } },
  { content: { label: 'Virgin Islands, U.S.', value: 'VI' } },
  { content: { label: 'Wallis and Futuna', value: 'WF' } },
  { content: { label: 'Western Sahara', value: 'EH' } },
  { content: { label: 'Yemen', value: 'YE' } },
  { content: { label: 'Zambia', value: 'ZM' } },
  { content: { label: 'Zimbabwe', value: 'ZW' } },
];

export default COUNTRIES_ARRAY;
